### ISSUE TITLE
Review of ToDo List Project

### ISSUE THREAD

**Issue by chepkok3** [frempongdev/To-Do-List-Review#2]
### ToDo List Review### 
@frempongdev Well done for the good work you have done. Everything looks impressive.
✔️You have followed the GitHub flow very well. 
✔️There are no linter errors in your work and the repository has been professionally documented as required. 
👏🏿 👍🏿
1. [x] However, despite all the functionalities working well and everything looking perfect, I think it would be better to introduce a delete button that appears when you click on the ellipsis-vertical icon as indicated in the minimalist demo image: 
<img width="842" alt="Screenshot 2023-01-30 at 18 40 50" src="https://user-images.githubusercontent.com/78428936/215523098-c1bb4f62-98ad-4405-b23a-7826f5a2ad04.png">

> You can achieve this by dynamically creating a button element with a function that enables deleting the item when the button thrash-can icon is pressed. 
2. [x]  Generally, your project is good and meets all the requirements and quality. Great work 
![image](https://user-images.githubusercontent.com/78428936/215525547-5a5c6b23-ada8-400a-a76a-fe4890dcfb76.png)

**Comment by frempongdev** [comment]
Hi @chepkok3 . thanks for checking up on my projects and pointing out what you have noticed. My 'Delete' button has been gracefully hidden under the 'Menu' button and it reveals itself when you click on the various task item. 😂 

Try it! 🔥

**Comment by frempongdev** [comment]
Hi @chepkok3 . thanks for checking up on my projects and pointing out what you have noticed. My 'Delete' button has been gracefully hidden under the 'Menu' button and it reveals itself when you click on the various task item. 😂

Try it! 🔥
